apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
data:
  flink-conf.yaml: |+
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 2
    jobmanager.memory.process.size: 1024m
    taskmanager.memory.process.size: 1024m
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  selector:
    app: flink
    component: jobmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: flink:1.17.2-scala_2.12
        args: ["jobmanager"]
        ports:
        - containerPort: 6123
        - containerPort: 8081
        env:
        - name: FLINK_PROPERTIES
          valueFrom:
            configMapKeyRef:
              name: flink-config
              key: flink-conf.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: flink:1.17.2-scala_2.12
        args: ["taskmanager"]
        env:
        - name: FLINK_PROPERTIES
          valueFrom:
            configMapKeyRef:
              name: flink-config
              key: flink-conf.yaml